### ISSUE TITLE
Image aspect ratio

### ISSUE THREAD

**Issue by mantelt** [ETHZ-RobotX/smb_assembly_manual#9]
Some images have a wrong aspect ratio (set in the html attributes):

- [x] gifs in  https://github.com/turcantuna/SMB_Assembly-Manual/wiki/Building-The-AL-Frame
- [x] images in https://github.com/turcantuna/SMB_Assembly-Manual/wiki/Building-Plexiglass-Stack#side-wall-stack

**Comment by turcantuna** [comment]
Improved the aspect ratio attribute of the images on that page, let me know if they still feel wrong.
